# CUDA
cuda_devices: '0'   # multi-gpu training is available

# Network
network:
  generator:
    k: 8
    feat_dim: 128
    res_conv_dim: 128
  discriminator: # discriminator is not used in test/evaluation
    k: 8
    feat_dim: 64
    res_conv_dim: 64

# Test dataset
dataset:
  input_dir: 'C:\Users\admin\Desktop\TTP_result\upsamlpling_fun\input'
  gt_dir: 'C:\Users\admin\Desktop\TTP_result\upsamlpling_fun\GT'
  pred_dir: 'C:\Users\admin\Desktop\TTP_result\upsamlpling_fun\ar-gcn-mrg100_retrain'

#load_model: 'C:\Users\admin\Desktop\ar-gcn_mrg100\ckpt\AR_GCN\pre_result_80_0.000410.pt'
load_model: 'C:\Users\admin\Desktop\ar-gcn_mrg100\ckpt\AR_GCN\result_40_1.345004.pt'

